# Generated by Django 3.1.6 on 2021-02-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20210216_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='posted_by',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to='blog_app.user'),
            preserve_default=False,
        ),
    ]
