# Generated by Django 3.1.6 on 2021-02-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_posts_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='blog_posts', to='blog_app.User'),
        ),
    ]
