# Generated by Django 3.1.6 on 2021-02-21 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_posts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default=str, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to='blog_app.User'),
        ),
    ]
