# Generated by Django 3.1.6 on 2021-02-21 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_auto_20210220_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='commented_by',
        ),
    ]
