# Generated by Django 3.1.6 on 2021-02-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20210221_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
